version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ../db_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:0.54
    ports:
      - "9018:8081"
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"

  python3:
    image: python/crewling
    build:
      context: .
      dockerfile: python/Dockerfile
    volumes:
      - ../src:/src
    depends_on:
      - "mongo"
    stdin_open: true
    tty: true
