version: '3.1'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p@$$w0rd
    ports:
      - "9017:27017"
    volumes:
      - ../db_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:0.54
    ports:
      - "9018:8081"
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: p@$$w0rd
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    restart: always

